### ISSUE TITLE
JellyLock

### ISSUE THREAD

**Issue by yasinchy2929** [MegaDevIOS/JellyLock-Reborn#1]
![6C2FDAFF-EAE0-4DBE-BD92-BD2F8551E63E](https://user-images.githubusercontent.com/81656937/113066553-9e3df980-91b2-11eb-9ac5-6f2ef6755c3b.png)
![22C20852-17D1-4D15-8C00-53BB0EAB5323](https://user-images.githubusercontent.com/81656937/113066558-9f6f2680-91b2-11eb-83da-1e16a766db99.png)

I switched off the jellyLock Reborn tweak and I respringed my iPhone and my lockscreen still showed the JellyLock Tweak.

**Comment by MegaDevIOS** [comment]
Issue found and fixed will be pushed in first update :) Thanks for the bug report!

**Comment by sabogalc** [comment]
https://user-images.githubusercontent.com/53708281/113463872-99698780-93f6-11eb-8bbc-8607fba3ccd8.mp4

I was about to report the same thing haha
