### ISSUE TITLE
Preference bundle not loading 

### ISSUE THREAD

**Issue by eliokarkar** [MegaDevIOS/JellyLock-Reborn#10]
iPhone 11 Pro Max running iOS 13.3
![3F82F2D7-D3AC-4E57-BDB9-1A0B12923066](https://user-images.githubusercontent.com/82239201/114235898-5bc5ab00-9970-11eb-9d5b-24197ad691ad.jpeg)

**Comment by MegaDevIOS** [comment]
ensure all dependencies are installed

**Comment by eliokarkar** [comment]
What dependencies should I install???
