### ISSUE TITLE
Sizing Issue

### ISSUE THREAD

**Issue by ShadowstarUnited** [MegaDevIOS/JellyLock-Reborn#2]
Everything works flawlessly, however the placement of the tweak on my iPhone 7 Plus is a little too far down as it cuts off the shortcuts at the bottom.

![C6932138-1879-408C-ABF0-968961EDAF56](https://user-images.githubusercontent.com/68189386/113067017-7733f780-91b3-11eb-8501-602c72d65feb.png)

**Comment by MegaDevIOS** [comment]
Will provide an offset option in either the next or update after. You will be able to offset everything in case it is too low for you
