### ISSUE TITLE
Appearance Setting causing reset

### ISSUE THREAD

**Issue by ShadowstarUnited** [MegaDevIOS/JellyLock-Reborn#3]
Upon changing the grabber size and then hitting respring, it resets the shortcuts and apps to null. iPhone 7 Plus iOS 14.2 - issue is reproducible.

**Comment by MegaDevIOS** [comment]
Seems to be an issue with libsparkapplist. I'm planning on switching to either libapplist or my own app picker that will automatically fix the issue :) will be available in either the first bug fix update or second
