### ISSUE TITLE
The circle blocks the "Press home to unlock" text on my iPhone 6S

### ISSUE THREAD

**Issue by sabogalc** [MegaDevIOS/JellyLock-Reborn#5]
Below is a screenshot of what it currently looks like, along with a mockup I made for an improvement
![IMG_0470](https://user-images.githubusercontent.com/53708281/113463897-da619c00-93f6-11eb-9820-0090e6e5e0ad.PNG)
![IMG_0470 - Copy](https://user-images.githubusercontent.com/53708281/113463899-dcc3f600-93f6-11eb-9b3b-b4016f7450e0.PNG)

**Comment by sabogalc** [comment]
Edit - Should I close this ticket because of [this](https://github.com/MegaDevIOS/JellyLock-Reborn/issues/2#issuecomment-811924075)?

**Comment by MegaDevIOS** [comment]
yess offset setting will be pushed shortly
