### ISSUE TITLE
Setting Shortcuts to 'None' bug

### ISSUE THREAD

**Issue by AymenKcm1** [MegaDevIOS/JellyLock-Reborn#8]
**Bug Description**
When setting the Shortcuts (flashlight & camera) to 'None' it leaves the right shortcut visible but not functional (even though the grabber snaps to it).

**To Reproduce**
Set both the Shortcuts to 'None' and respring.

**Expected behavior**
**Both** shortcuts are hidden.

**Screenshots**
![image](https://user-images.githubusercontent.com/67245917/113520487-4d038080-958b-11eb-9813-ed5798556cd8.png)

**iDevice Information:**

Device: iPhone 12 Pro Max (iPhone13,4)
OS: iOS 14.3
JellyLock Reborn Version : v1.0
Jailbreak Used: Taurine v1.0.1

**Additional context**
After hiding the shortcuts, the circular line is exposed to be not perfectly circular. There's a "dent" hidden behind where the shortcuts should be.

![image](https://user-images.githubusercontent.com/67245917/113520613-2c87f600-958c-11eb-8d76-01b82f4bd78d.jpeg)

**Comment by MegaDevIOS** [comment]
Fixed in 1.1
