### ISSUE TITLE
[Enhancement] Display selected app name

### ISSUE THREAD

**Issue by AymenKcm1** [MegaDevIOS/JellyLock-Reborn#9]
It would be useful to show the selected app name in front of " App Shortcut # " 

Example: 

App Shortcut 1 : Appstore
App Shortcut 2 : Music
...

![image](https://user-images.githubusercontent.com/67245917/113525144-2f461380-95ab-11eb-8637-99919dac443a.png)

**Comment by MegaDevIOS** [comment]
Done will be released in 1.1![image](https://user-images.githubusercontent.com/61117573/114307986-820b5800-9ae2-11eb-9c37-54e909d1ecda.png)
